//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TeX.InfoReset {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuariosSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Usuarios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscaPorLoginCompletoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaPorLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaPorEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuariosDoGrupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuariosEmailDoGrupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFuncionariosComOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFuncionariosContendoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFuncionariosSGAComOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFuncionariosSGAContendoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarNomesComOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarNomesContendoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodosAtivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodosInativosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodosFuncionariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarGruposDeUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaFuncionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDadosDeUsuariosComOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDadosDeUsuariosContendoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticaADAGOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarInformacoesParaResetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Usuarios() {
            this.Url = global::TeX.Properties.Settings.Default.TeX_InfoReset_Usuarios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscaPorLoginCompletoCompletedEventHandler BuscaPorLoginCompletoCompleted;
        
        /// <remarks/>
        public event BuscaPorLoginCompletedEventHandler BuscaPorLoginCompleted;
        
        /// <remarks/>
        public event BuscaPorIdCompletedEventHandler BuscaPorIdCompleted;
        
        /// <remarks/>
        public event BuscaPorEmailCompletedEventHandler BuscaPorEmailCompleted;
        
        /// <remarks/>
        public event BuscarUsuariosDoGrupoCompletedEventHandler BuscarUsuariosDoGrupoCompleted;
        
        /// <remarks/>
        public event BuscarUsuariosEmailDoGrupoCompletedEventHandler BuscarUsuariosEmailDoGrupoCompleted;
        
        /// <remarks/>
        public event ListarFuncionariosComCompletedEventHandler ListarFuncionariosComCompleted;
        
        /// <remarks/>
        public event ListarFuncionariosContendoCompletedEventHandler ListarFuncionariosContendoCompleted;
        
        /// <remarks/>
        public event ListarFuncionariosSGAComCompletedEventHandler ListarFuncionariosSGAComCompleted;
        
        /// <remarks/>
        public event ListarFuncionariosSGAContendoCompletedEventHandler ListarFuncionariosSGAContendoCompleted;
        
        /// <remarks/>
        public event ListarNomesComCompletedEventHandler ListarNomesComCompleted;
        
        /// <remarks/>
        public event ListarNomesContendoCompletedEventHandler ListarNomesContendoCompleted;
        
        /// <remarks/>
        public event TodosCompletedEventHandler TodosCompleted;
        
        /// <remarks/>
        public event TodosAtivosCompletedEventHandler TodosAtivosCompleted;
        
        /// <remarks/>
        public event TodosInativosCompletedEventHandler TodosInativosCompleted;
        
        /// <remarks/>
        public event TodosFuncionariosCompletedEventHandler TodosFuncionariosCompleted;
        
        /// <remarks/>
        public event ListarGruposDeUsuariosCompletedEventHandler ListarGruposDeUsuariosCompleted;
        
        /// <remarks/>
        public event ValidaFuncionarioCompletedEventHandler ValidaFuncionarioCompleted;
        
        /// <remarks/>
        public event ListarDadosDeUsuariosComCompletedEventHandler ListarDadosDeUsuariosComCompleted;
        
        /// <remarks/>
        public event ListarDadosDeUsuariosContendoCompletedEventHandler ListarDadosDeUsuariosContendoCompleted;
        
        /// <remarks/>
        public event AutenticaADAGCompletedEventHandler AutenticaADAGCompleted;
        
        /// <remarks/>
        public event ConfirmarInformacoesParaResetCompletedEventHandler ConfirmarInformacoesParaResetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaPorLoginCompleto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario BuscaPorLoginCompleto(string dominio, string login) {
            object[] results = this.Invoke("BuscaPorLoginCompleto", new object[] {
                        dominio,
                        login});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaPorLoginCompletoAsync(string dominio, string login) {
            this.BuscaPorLoginCompletoAsync(dominio, login, null);
        }
        
        /// <remarks/>
        public void BuscaPorLoginCompletoAsync(string dominio, string login, object userState) {
            if ((this.BuscaPorLoginCompletoOperationCompleted == null)) {
                this.BuscaPorLoginCompletoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaPorLoginCompletoOperationCompleted);
            }
            this.InvokeAsync("BuscaPorLoginCompleto", new object[] {
                        dominio,
                        login}, this.BuscaPorLoginCompletoOperationCompleted, userState);
        }
        
        private void OnBuscaPorLoginCompletoOperationCompleted(object arg) {
            if ((this.BuscaPorLoginCompletoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaPorLoginCompletoCompleted(this, new BuscaPorLoginCompletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaPorLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario BuscaPorLogin(string login) {
            object[] results = this.Invoke("BuscaPorLogin", new object[] {
                        login});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaPorLoginAsync(string login) {
            this.BuscaPorLoginAsync(login, null);
        }
        
        /// <remarks/>
        public void BuscaPorLoginAsync(string login, object userState) {
            if ((this.BuscaPorLoginOperationCompleted == null)) {
                this.BuscaPorLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaPorLoginOperationCompleted);
            }
            this.InvokeAsync("BuscaPorLogin", new object[] {
                        login}, this.BuscaPorLoginOperationCompleted, userState);
        }
        
        private void OnBuscaPorLoginOperationCompleted(object arg) {
            if ((this.BuscaPorLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaPorLoginCompleted(this, new BuscaPorLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario BuscaPorId(string id) {
            object[] results = this.Invoke("BuscaPorId", new object[] {
                        id});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaPorIdAsync(string id) {
            this.BuscaPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void BuscaPorIdAsync(string id, object userState) {
            if ((this.BuscaPorIdOperationCompleted == null)) {
                this.BuscaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaPorIdOperationCompleted);
            }
            this.InvokeAsync("BuscaPorId", new object[] {
                        id}, this.BuscaPorIdOperationCompleted, userState);
        }
        
        private void OnBuscaPorIdOperationCompleted(object arg) {
            if ((this.BuscaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaPorIdCompleted(this, new BuscaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaPorEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario BuscaPorEmail(string email) {
            object[] results = this.Invoke("BuscaPorEmail", new object[] {
                        email});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaPorEmailAsync(string email) {
            this.BuscaPorEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void BuscaPorEmailAsync(string email, object userState) {
            if ((this.BuscaPorEmailOperationCompleted == null)) {
                this.BuscaPorEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaPorEmailOperationCompleted);
            }
            this.InvokeAsync("BuscaPorEmail", new object[] {
                        email}, this.BuscaPorEmailOperationCompleted, userState);
        }
        
        private void OnBuscaPorEmailOperationCompleted(object arg) {
            if ((this.BuscaPorEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaPorEmailCompleted(this, new BuscaPorEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuariosDoGrupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarUsuariosDoGrupo(string nomeGrupo) {
            object[] results = this.Invoke("BuscarUsuariosDoGrupo", new object[] {
                        nomeGrupo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuariosDoGrupoAsync(string nomeGrupo) {
            this.BuscarUsuariosDoGrupoAsync(nomeGrupo, null);
        }
        
        /// <remarks/>
        public void BuscarUsuariosDoGrupoAsync(string nomeGrupo, object userState) {
            if ((this.BuscarUsuariosDoGrupoOperationCompleted == null)) {
                this.BuscarUsuariosDoGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuariosDoGrupoOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuariosDoGrupo", new object[] {
                        nomeGrupo}, this.BuscarUsuariosDoGrupoOperationCompleted, userState);
        }
        
        private void OnBuscarUsuariosDoGrupoOperationCompleted(object arg) {
            if ((this.BuscarUsuariosDoGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuariosDoGrupoCompleted(this, new BuscarUsuariosDoGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuariosEmailDoGrupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarUsuariosEmailDoGrupo(string nomeGrupo) {
            object[] results = this.Invoke("BuscarUsuariosEmailDoGrupo", new object[] {
                        nomeGrupo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuariosEmailDoGrupoAsync(string nomeGrupo) {
            this.BuscarUsuariosEmailDoGrupoAsync(nomeGrupo, null);
        }
        
        /// <remarks/>
        public void BuscarUsuariosEmailDoGrupoAsync(string nomeGrupo, object userState) {
            if ((this.BuscarUsuariosEmailDoGrupoOperationCompleted == null)) {
                this.BuscarUsuariosEmailDoGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuariosEmailDoGrupoOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuariosEmailDoGrupo", new object[] {
                        nomeGrupo}, this.BuscarUsuariosEmailDoGrupoOperationCompleted, userState);
        }
        
        private void OnBuscarUsuariosEmailDoGrupoOperationCompleted(object arg) {
            if ((this.BuscarUsuariosEmailDoGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuariosEmailDoGrupoCompleted(this, new BuscarUsuariosEmailDoGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarFuncionariosCom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarFuncionariosCom(string inicio) {
            object[] results = this.Invoke("ListarFuncionariosCom", new object[] {
                        inicio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarFuncionariosComAsync(string inicio) {
            this.ListarFuncionariosComAsync(inicio, null);
        }
        
        /// <remarks/>
        public void ListarFuncionariosComAsync(string inicio, object userState) {
            if ((this.ListarFuncionariosComOperationCompleted == null)) {
                this.ListarFuncionariosComOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFuncionariosComOperationCompleted);
            }
            this.InvokeAsync("ListarFuncionariosCom", new object[] {
                        inicio}, this.ListarFuncionariosComOperationCompleted, userState);
        }
        
        private void OnListarFuncionariosComOperationCompleted(object arg) {
            if ((this.ListarFuncionariosComCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFuncionariosComCompleted(this, new ListarFuncionariosComCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarFuncionariosContendo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarFuncionariosContendo(string inicio) {
            object[] results = this.Invoke("ListarFuncionariosContendo", new object[] {
                        inicio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarFuncionariosContendoAsync(string inicio) {
            this.ListarFuncionariosContendoAsync(inicio, null);
        }
        
        /// <remarks/>
        public void ListarFuncionariosContendoAsync(string inicio, object userState) {
            if ((this.ListarFuncionariosContendoOperationCompleted == null)) {
                this.ListarFuncionariosContendoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFuncionariosContendoOperationCompleted);
            }
            this.InvokeAsync("ListarFuncionariosContendo", new object[] {
                        inicio}, this.ListarFuncionariosContendoOperationCompleted, userState);
        }
        
        private void OnListarFuncionariosContendoOperationCompleted(object arg) {
            if ((this.ListarFuncionariosContendoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFuncionariosContendoCompleted(this, new ListarFuncionariosContendoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarFuncionariosSGACom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarFuncionariosSGACom(string nome) {
            object[] results = this.Invoke("ListarFuncionariosSGACom", new object[] {
                        nome});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarFuncionariosSGAComAsync(string nome) {
            this.ListarFuncionariosSGAComAsync(nome, null);
        }
        
        /// <remarks/>
        public void ListarFuncionariosSGAComAsync(string nome, object userState) {
            if ((this.ListarFuncionariosSGAComOperationCompleted == null)) {
                this.ListarFuncionariosSGAComOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFuncionariosSGAComOperationCompleted);
            }
            this.InvokeAsync("ListarFuncionariosSGACom", new object[] {
                        nome}, this.ListarFuncionariosSGAComOperationCompleted, userState);
        }
        
        private void OnListarFuncionariosSGAComOperationCompleted(object arg) {
            if ((this.ListarFuncionariosSGAComCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFuncionariosSGAComCompleted(this, new ListarFuncionariosSGAComCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarFuncionariosSGAContendo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarFuncionariosSGAContendo(string nome) {
            object[] results = this.Invoke("ListarFuncionariosSGAContendo", new object[] {
                        nome});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarFuncionariosSGAContendoAsync(string nome) {
            this.ListarFuncionariosSGAContendoAsync(nome, null);
        }
        
        /// <remarks/>
        public void ListarFuncionariosSGAContendoAsync(string nome, object userState) {
            if ((this.ListarFuncionariosSGAContendoOperationCompleted == null)) {
                this.ListarFuncionariosSGAContendoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFuncionariosSGAContendoOperationCompleted);
            }
            this.InvokeAsync("ListarFuncionariosSGAContendo", new object[] {
                        nome}, this.ListarFuncionariosSGAContendoOperationCompleted, userState);
        }
        
        private void OnListarFuncionariosSGAContendoOperationCompleted(object arg) {
            if ((this.ListarFuncionariosSGAContendoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFuncionariosSGAContendoCompleted(this, new ListarFuncionariosSGAContendoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarNomesCom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarNomesCom(string inicio) {
            object[] results = this.Invoke("ListarNomesCom", new object[] {
                        inicio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarNomesComAsync(string inicio) {
            this.ListarNomesComAsync(inicio, null);
        }
        
        /// <remarks/>
        public void ListarNomesComAsync(string inicio, object userState) {
            if ((this.ListarNomesComOperationCompleted == null)) {
                this.ListarNomesComOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarNomesComOperationCompleted);
            }
            this.InvokeAsync("ListarNomesCom", new object[] {
                        inicio}, this.ListarNomesComOperationCompleted, userState);
        }
        
        private void OnListarNomesComOperationCompleted(object arg) {
            if ((this.ListarNomesComCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarNomesComCompleted(this, new ListarNomesComCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarNomesContendo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarNomesContendo(string inicio) {
            object[] results = this.Invoke("ListarNomesContendo", new object[] {
                        inicio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarNomesContendoAsync(string inicio) {
            this.ListarNomesContendoAsync(inicio, null);
        }
        
        /// <remarks/>
        public void ListarNomesContendoAsync(string inicio, object userState) {
            if ((this.ListarNomesContendoOperationCompleted == null)) {
                this.ListarNomesContendoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarNomesContendoOperationCompleted);
            }
            this.InvokeAsync("ListarNomesContendo", new object[] {
                        inicio}, this.ListarNomesContendoOperationCompleted, userState);
        }
        
        private void OnListarNomesContendoOperationCompleted(object arg) {
            if ((this.ListarNomesContendoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarNomesContendoCompleted(this, new ListarNomesContendoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Todos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Todos() {
            object[] results = this.Invoke("Todos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TodosAsync() {
            this.TodosAsync(null);
        }
        
        /// <remarks/>
        public void TodosAsync(object userState) {
            if ((this.TodosOperationCompleted == null)) {
                this.TodosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodosOperationCompleted);
            }
            this.InvokeAsync("Todos", new object[0], this.TodosOperationCompleted, userState);
        }
        
        private void OnTodosOperationCompleted(object arg) {
            if ((this.TodosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodosCompleted(this, new TodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodosAtivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TodosAtivos() {
            object[] results = this.Invoke("TodosAtivos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TodosAtivosAsync() {
            this.TodosAtivosAsync(null);
        }
        
        /// <remarks/>
        public void TodosAtivosAsync(object userState) {
            if ((this.TodosAtivosOperationCompleted == null)) {
                this.TodosAtivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodosAtivosOperationCompleted);
            }
            this.InvokeAsync("TodosAtivos", new object[0], this.TodosAtivosOperationCompleted, userState);
        }
        
        private void OnTodosAtivosOperationCompleted(object arg) {
            if ((this.TodosAtivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodosAtivosCompleted(this, new TodosAtivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodosInativos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TodosInativos() {
            object[] results = this.Invoke("TodosInativos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TodosInativosAsync() {
            this.TodosInativosAsync(null);
        }
        
        /// <remarks/>
        public void TodosInativosAsync(object userState) {
            if ((this.TodosInativosOperationCompleted == null)) {
                this.TodosInativosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodosInativosOperationCompleted);
            }
            this.InvokeAsync("TodosInativos", new object[0], this.TodosInativosOperationCompleted, userState);
        }
        
        private void OnTodosInativosOperationCompleted(object arg) {
            if ((this.TodosInativosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodosInativosCompleted(this, new TodosInativosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodosFuncionarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TodosFuncionarios() {
            object[] results = this.Invoke("TodosFuncionarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TodosFuncionariosAsync() {
            this.TodosFuncionariosAsync(null);
        }
        
        /// <remarks/>
        public void TodosFuncionariosAsync(object userState) {
            if ((this.TodosFuncionariosOperationCompleted == null)) {
                this.TodosFuncionariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodosFuncionariosOperationCompleted);
            }
            this.InvokeAsync("TodosFuncionarios", new object[0], this.TodosFuncionariosOperationCompleted, userState);
        }
        
        private void OnTodosFuncionariosOperationCompleted(object arg) {
            if ((this.TodosFuncionariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodosFuncionariosCompleted(this, new TodosFuncionariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarGruposDeUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarGruposDeUsuarios(string grupo) {
            object[] results = this.Invoke("ListarGruposDeUsuarios", new object[] {
                        grupo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarGruposDeUsuariosAsync(string grupo) {
            this.ListarGruposDeUsuariosAsync(grupo, null);
        }
        
        /// <remarks/>
        public void ListarGruposDeUsuariosAsync(string grupo, object userState) {
            if ((this.ListarGruposDeUsuariosOperationCompleted == null)) {
                this.ListarGruposDeUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarGruposDeUsuariosOperationCompleted);
            }
            this.InvokeAsync("ListarGruposDeUsuarios", new object[] {
                        grupo}, this.ListarGruposDeUsuariosOperationCompleted, userState);
        }
        
        private void OnListarGruposDeUsuariosOperationCompleted(object arg) {
            if ((this.ListarGruposDeUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarGruposDeUsuariosCompleted(this, new ListarGruposDeUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaFuncionario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaFuncionario(string login) {
            object[] results = this.Invoke("ValidaFuncionario", new object[] {
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaFuncionarioAsync(string login) {
            this.ValidaFuncionarioAsync(login, null);
        }
        
        /// <remarks/>
        public void ValidaFuncionarioAsync(string login, object userState) {
            if ((this.ValidaFuncionarioOperationCompleted == null)) {
                this.ValidaFuncionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaFuncionarioOperationCompleted);
            }
            this.InvokeAsync("ValidaFuncionario", new object[] {
                        login}, this.ValidaFuncionarioOperationCompleted, userState);
        }
        
        private void OnValidaFuncionarioOperationCompleted(object arg) {
            if ((this.ValidaFuncionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaFuncionarioCompleted(this, new ValidaFuncionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDadosDeUsuariosCom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] ListarDadosDeUsuariosCom(string nome) {
            object[] results = this.Invoke("ListarDadosDeUsuariosCom", new object[] {
                        nome});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDadosDeUsuariosComAsync(string nome) {
            this.ListarDadosDeUsuariosComAsync(nome, null);
        }
        
        /// <remarks/>
        public void ListarDadosDeUsuariosComAsync(string nome, object userState) {
            if ((this.ListarDadosDeUsuariosComOperationCompleted == null)) {
                this.ListarDadosDeUsuariosComOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDadosDeUsuariosComOperationCompleted);
            }
            this.InvokeAsync("ListarDadosDeUsuariosCom", new object[] {
                        nome}, this.ListarDadosDeUsuariosComOperationCompleted, userState);
        }
        
        private void OnListarDadosDeUsuariosComOperationCompleted(object arg) {
            if ((this.ListarDadosDeUsuariosComCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDadosDeUsuariosComCompleted(this, new ListarDadosDeUsuariosComCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarDadosDeUsuariosContendo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] ListarDadosDeUsuariosContendo(string nome) {
            object[] results = this.Invoke("ListarDadosDeUsuariosContendo", new object[] {
                        nome});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDadosDeUsuariosContendoAsync(string nome) {
            this.ListarDadosDeUsuariosContendoAsync(nome, null);
        }
        
        /// <remarks/>
        public void ListarDadosDeUsuariosContendoAsync(string nome, object userState) {
            if ((this.ListarDadosDeUsuariosContendoOperationCompleted == null)) {
                this.ListarDadosDeUsuariosContendoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDadosDeUsuariosContendoOperationCompleted);
            }
            this.InvokeAsync("ListarDadosDeUsuariosContendo", new object[] {
                        nome}, this.ListarDadosDeUsuariosContendoOperationCompleted, userState);
        }
        
        private void OnListarDadosDeUsuariosContendoOperationCompleted(object arg) {
            if ((this.ListarDadosDeUsuariosContendoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDadosDeUsuariosContendoCompleted(this, new ListarDadosDeUsuariosContendoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticaADAG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AutenticaADAG(string login, string senha) {
            object[] results = this.Invoke("AutenticaADAG", new object[] {
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticaADAGAsync(string login, string senha) {
            this.AutenticaADAGAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void AutenticaADAGAsync(string login, string senha, object userState) {
            if ((this.AutenticaADAGOperationCompleted == null)) {
                this.AutenticaADAGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticaADAGOperationCompleted);
            }
            this.InvokeAsync("AutenticaADAG", new object[] {
                        login,
                        senha}, this.AutenticaADAGOperationCompleted, userState);
        }
        
        private void OnAutenticaADAGOperationCompleted(object arg) {
            if ((this.AutenticaADAGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticaADAGCompleted(this, new AutenticaADAGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarInformacoesParaReset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Confirmacao ConfirmarInformacoesParaReset(string matricula, string cpf, string rg, string idade) {
            object[] results = this.Invoke("ConfirmarInformacoesParaReset", new object[] {
                        matricula,
                        cpf,
                        rg,
                        idade});
            return ((Confirmacao)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarInformacoesParaResetAsync(string matricula, string cpf, string rg, string idade) {
            this.ConfirmarInformacoesParaResetAsync(matricula, cpf, rg, idade, null);
        }
        
        /// <remarks/>
        public void ConfirmarInformacoesParaResetAsync(string matricula, string cpf, string rg, string idade, object userState) {
            if ((this.ConfirmarInformacoesParaResetOperationCompleted == null)) {
                this.ConfirmarInformacoesParaResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarInformacoesParaResetOperationCompleted);
            }
            this.InvokeAsync("ConfirmarInformacoesParaReset", new object[] {
                        matricula,
                        cpf,
                        rg,
                        idade}, this.ConfirmarInformacoesParaResetOperationCompleted, userState);
        }
        
        private void OnConfirmarInformacoesParaResetOperationCompleted(object arg) {
            if ((this.ConfirmarInformacoesParaResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarInformacoesParaResetCompleted(this, new ConfirmarInformacoesParaResetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string idField;
        
        private string nomeField;
        
        private string primeiroNomeField;
        
        private string ultimoNomeField;
        
        private string dominioField;
        
        private string loginField;
        
        private string mailField;
        
        private string matriculaField;
        
        private string statusField;
        
        private string departamentoField;
        
        private string telefoneField;
        
        private System.DateTime ultimaAtualizacaoField;
        
        private object[] gruposField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeiroNome {
            get {
                return this.primeiroNomeField;
            }
            set {
                this.primeiroNomeField = value;
            }
        }
        
        /// <remarks/>
        public string UltimoNome {
            get {
                return this.ultimoNomeField;
            }
            set {
                this.ultimoNomeField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UltimaAtualizacao {
            get {
                return this.ultimaAtualizacaoField;
            }
            set {
                this.ultimaAtualizacaoField = value;
            }
        }
        
        /// <remarks/>
        public object[] Grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Confirmacao {
        
        private int codigoField;
        
        private string mensagemField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscaPorLoginCompletoCompletedEventHandler(object sender, BuscaPorLoginCompletoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaPorLoginCompletoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaPorLoginCompletoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscaPorLoginCompletedEventHandler(object sender, BuscaPorLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaPorLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaPorLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscaPorIdCompletedEventHandler(object sender, BuscaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscaPorEmailCompletedEventHandler(object sender, BuscaPorEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaPorEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaPorEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscarUsuariosDoGrupoCompletedEventHandler(object sender, BuscarUsuariosDoGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuariosDoGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuariosDoGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BuscarUsuariosEmailDoGrupoCompletedEventHandler(object sender, BuscarUsuariosEmailDoGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuariosEmailDoGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuariosEmailDoGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFuncionariosComCompletedEventHandler(object sender, ListarFuncionariosComCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFuncionariosComCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFuncionariosComCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFuncionariosContendoCompletedEventHandler(object sender, ListarFuncionariosContendoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFuncionariosContendoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFuncionariosContendoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFuncionariosSGAComCompletedEventHandler(object sender, ListarFuncionariosSGAComCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFuncionariosSGAComCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFuncionariosSGAComCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFuncionariosSGAContendoCompletedEventHandler(object sender, ListarFuncionariosSGAContendoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFuncionariosSGAContendoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFuncionariosSGAContendoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarNomesComCompletedEventHandler(object sender, ListarNomesComCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarNomesComCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarNomesComCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarNomesContendoCompletedEventHandler(object sender, ListarNomesContendoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarNomesContendoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarNomesContendoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TodosCompletedEventHandler(object sender, TodosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TodosAtivosCompletedEventHandler(object sender, TodosAtivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodosAtivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodosAtivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TodosInativosCompletedEventHandler(object sender, TodosInativosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodosInativosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodosInativosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TodosFuncionariosCompletedEventHandler(object sender, TodosFuncionariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodosFuncionariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodosFuncionariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarGruposDeUsuariosCompletedEventHandler(object sender, ListarGruposDeUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarGruposDeUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarGruposDeUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidaFuncionarioCompletedEventHandler(object sender, ValidaFuncionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarDadosDeUsuariosComCompletedEventHandler(object sender, ListarDadosDeUsuariosComCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDadosDeUsuariosComCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDadosDeUsuariosComCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarDadosDeUsuariosContendoCompletedEventHandler(object sender, ListarDadosDeUsuariosContendoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDadosDeUsuariosContendoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDadosDeUsuariosContendoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AutenticaADAGCompletedEventHandler(object sender, AutenticaADAGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticaADAGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticaADAGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConfirmarInformacoesParaResetCompletedEventHandler(object sender, ConfirmarInformacoesParaResetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarInformacoesParaResetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarInformacoesParaResetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Confirmacao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Confirmacao)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591